spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true #sysout? ??
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug #logger? ??
    org.hibernate.type: trace